# -*- coding: utf-8 -*-
"""recursion_ejemplos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_WogPxFvnIqxYI_qAIApgqpcQGwcz4q
"""

# recursion sin acumulador

def factorial(n):
  if n == 0:
    return 1
  return n*factorial(n-1)
print(factorial(5)) # 120

# recursion con acumulador

def factorial_tail(n, acumulador=1):
  if n == 0:
    return acumulador
  return factorial_tail(n-1, n*acumulador)
print(factorial_tail(5)) # 120

# recursion con resultado en el cuerpo

def factorial_body(n):
  resultado = 1
  if n > 0:
    resultado = n*factorial_body(n-1)
  return resultado
print(factorial_body(5)) # 120

def factorial(n):
  assert isinstance(n, int) and n >= 0, "Error, n debe ser positivo"
  if n == 0:
    return 1
  return n*factorial(n-1)
print(factorial(5)) # 120

def contar_digitos(n):
  if n == 0:
    return 0
  return 1+contar_digitos(n//10)
print(contar_digitos(41156)) # 5

def palabra_alreves(p1):
  if len(p1) == 1:
    return p1
  return p1[-1]+palabra_alreves(p1[:-1])
print(palabra_alreves("mateo")) # oetam